### Get all credentials

GET http://localhost:3000/api/credentials
Authorization:{{$dotenv MASTERPASSWORD}}

### Get credential

GET http://localhost:3000/api/credentials/bla
Authorization:{{$dotenv MASTERPASSWORD}}

### Add single credential

POST http://localhost:3000/api/credentials
Content-Type: application/json 
Authorization:{{$dotenv MASTERPASSWORD}}

{
    "service": "blupp", 
    "username": "aron", 
    "password": "1234"
}

### Delete single credential

DELETE http://localhost:3000/api/credentials/bla
Authorization:{{$dotenv MASTERPASSWORD}}

### Update single credential

PUT http://localhost:3000/api/credentials/blup
Content-Type: application/json 
Authorization:{{$dotenv MASTERPASSWORD}}

{
    "service": "bla", 
    "username": "Aron", 
    "password": "qwertz"
}