### Get all credentials

GET http://localhost:3000/api/credentials


### Get credential

GET http://localhost:3000/api/credentials/google

### Add single credential

POST http://localhost:3000/api/credentials

Content-Type: application/json 
{
    "service": "google", 
    "username": "", 
    "password": ""
}
